import argparse
import json
import re
from pathlib import Path

from lib_reimbursement import normalize_record, read_csv_records, read_json, write_json


AMOUNT_RE = re.compile(r"(?:¥|￥|RMB|CNY)?\s*([-+]?\d+(?:\.\d{1,2})?)", re.I)


def records_from_json(path):
    data = read_json(path)
    if isinstance(data, list):
        items = data
    elif isinstance(data, dict):
        items = data.get("records") or data.get("items") or []
    else:
        items = []
    return [normalize_record(item, source_file=str(path), default_evidence_type="structured_data") for item in items]


def records_from_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(normalize_record(json.loads(line), source_file=str(path), default_evidence_type="structured_data"))
    return rows


def records_from_csv(path):
    return [normalize_record(row, source_file=str(path), default_evidence_type="structured_data") for row in read_csv_records(path)]


def records_from_text(path):
    records = []
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            amount = None
            match = AMOUNT_RE.search(line.replace(",", ""))
            if match:
                amount = match.group(1)
            if amount is None:
                continue
            records.append(
                normalize_record(
                    {
                        "source_file": str(path),
                        "merchant": line[:80],
                        "amount": amount,
                        "confidence": 0.35,
                        "reason": f"Extracted from text line {line_no}; needs review.",
                        "warnings": ["text_regex_extraction"],
                    },
                    source_file=str(path),
                    default_evidence_type="text",
                )
            )
    return records


def placeholder_for_visual_file(material):
    return normalize_record(
        {
            "id": f"visual-{material['sha256'][:12]}",
            "source_file": material["path"],
            "merchant": "",
            "amount": None,
            "category": "",
            "evidence_type": material["kind"],
            "confidence": 0,
            "suggested_action": "review",
            "reason": "Visual or document file requires agent OCR/vision extraction.",
            "warnings": ["vision_required"],
        },
        source_file=material["path"],
        default_evidence_type=material["kind"],
    )


def extract(materials, agent_records=None):
    records = []
    for material in materials.get("files", []):
        path = Path(material["path"])
        suffix = path.suffix.lower()
        try:
            if suffix == ".json":
                records.extend(records_from_json(path))
            elif suffix == ".jsonl":
                records.extend(records_from_jsonl(path))
            elif suffix == ".csv":
                records.extend(records_from_csv(path))
            elif suffix in {".txt", ".md"}:
                records.extend(records_from_text(path))
            elif material.get("kind") in {"image", "document"}:
                records.append(placeholder_for_visual_file(material))
        except Exception as exc:
            records.append(
                normalize_record(
                    {
                        "source_file": str(path),
                        "evidence_type": material.get("kind", "unknown"),
                        "confidence": 0,
                        "suggested_action": "review",
                        "reason": f"Extraction failed: {exc}",
                        "warnings": ["extraction_failed"],
                    },
                    source_file=str(path),
                )
            )
    if agent_records:
        data = read_json(agent_records)
        agent_items = data.get("records", data) if isinstance(data, dict) else data
        for item in agent_items:
            records.append(normalize_record(item, default_evidence_type=item.get("evidence_type", "agent_vision")))
    return {"records": records}


def main():
    parser = argparse.ArgumentParser(description="Extract structured reimbursement records.")
    parser.add_argument("--materials", required=True, help="Materials manifest JSON from scan_materials.py.")
    parser.add_argument("--agent-records", help="Optional records JSON generated by an agent/OCR model.")
    parser.add_argument("--output", required=True, help="Output extracted claim JSON.")
    args = parser.parse_args()
    materials = read_json(args.materials)
    write_json(args.output, extract(materials, args.agent_records))


if __name__ == "__main__":
    main()

